// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ports} from '../models';
import {context} from '../models';

export function CreateEnvironment(arg1:ports.Environment):Promise<ports.Environment>;

export function CreateLoad(arg1:ports.Load):Promise<ports.Load>;

export function CreateRifle(arg1:ports.Rifle):Promise<ports.Rifle>;

export function CreateScenario(arg1:ports.Scenario):Promise<ports.Scenario>;

export function Greet(arg1:string):Promise<string>;

export function ListEnvironments():Promise<Array<ports.Environment>>;

export function ListLoads():Promise<Array<ports.Load>>;

export function ListRifles():Promise<Array<ports.Rifle>>;

export function ListScenarios():Promise<Array<ports.Scenario>>;

export function Start(arg1:context.Context):Promise<void>;
