// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateEnvironment(arg1) {
  return window['go']['main']['App']['CreateEnvironment'](arg1);
}

export function CreateLoad(arg1) {
  return window['go']['main']['App']['CreateLoad'](arg1);
}

export function CreateRifle(arg1) {
  return window['go']['main']['App']['CreateRifle'](arg1);
}

export function CreateScenario(arg1) {
  return window['go']['main']['App']['CreateScenario'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListEnvironments() {
  return window['go']['main']['App']['ListEnvironments']();
}

export function ListLoads() {
  return window['go']['main']['App']['ListLoads']();
}

export function ListRifles() {
  return window['go']['main']['App']['ListRifles']();
}

export function ListScenarios() {
  return window['go']['main']['App']['ListScenarios']();
}

export function Start(arg1) {
  return window['go']['main']['App']['Start'](arg1);
}
